basePath: /
definitions:
  domain.CostInfoPayload:
    properties:
      courier:
        type: string
      destination:
        type: integer
      origin:
        type: integer
      weight:
        type: number
    required:
    - destination
    - origin
    - weight
    type: object
  domain.CreateBankDto:
    properties:
      bankCode:
        type: string
      bankName:
        type: string
    required:
    - bankCode
    - bankName
    type: object
  domain.PayloadLogin:
    properties:
      emailName:
        example: me@mail.com
        type: string
      password:
        example: securePassword
        type: string
    required:
    - emailName
    - password
    type: object
  domain.PayloadRegister:
    properties:
      emailName:
        example: me@mail.com
        type: string
      password:
        example: securePassword
        type: string
    required:
    - emailName
    - password
    type: object
  domain.SendEmailPayload:
    properties:
      body:
        type: string
      recipient:
        items:
          type: string
        type: array
      subject:
        type: string
    required:
    - body
    - subject
    type: object
  domain.UpdateBankDto:
    properties:
      bankName:
        type: string
    required:
    - bankName
    type: object
  response.ResponseProperties:
    properties:
      data: {}
      httpStatus:
        type: integer
      message:
        type: string
      resultCode:
        type: string
    type: object
info:
  contact: {}
  title: Celestialsoftware API
  version: v1.0
paths:
  /auth/login:
    post:
      parameters:
      - description: Login info
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.PayloadLogin'
      produces:
      - application/json
      responses:
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResponseProperties'
      summary: User Authentication
      tags:
      - Authentication
  /auth/register:
    post:
      parameters:
      - description: Login info
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.PayloadRegister'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ResponseProperties'
      summary: User Registration
      tags:
      - Authentication
  /bank:
    get:
      description: Get Bank Collection
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "400":
          description: General Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "401":
          description: Authentication Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
      summary: Get Bank Collection
      tags:
      - Bank
    post:
      description: Create New Bank
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: Bank Information
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.CreateBankDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "400":
          description: General Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "401":
          description: Authentication Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
      summary: Create New Bank
      tags:
      - Bank
  /bank/{oid}:
    delete:
      description: Detail Bank
      parameters:
      - description: oid of Bank
        in: path
        name: oid
        required: true
        type: string
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "400":
          description: General Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "401":
          description: Authentication Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
      summary: Delete Bank
      tags:
      - Bank
    get:
      description: Detail Bank
      parameters:
      - description: oid of Bank
        in: path
        name: oid
        required: true
        type: string
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "400":
          description: General Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "401":
          description: Authentication Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
      summary: Detail Bank
      tags:
      - Bank
    patch:
      description: Update Bank
      parameters:
      - description: oid of Bank
        in: path
        name: oid
        required: true
        type: string
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: New Bank Information
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateBankDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "400":
          description: General Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
        "401":
          description: Authentication Error
          schema:
            $ref: '#/definitions/response.ResponseProperties'
      summary: Update Bank
      tags:
      - Bank
  /file:
    get:
      description: Get File Collection
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get File Collection
      tags:
      - File
    post:
      description: Upload new File
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: File to upload
        in: formData
        name: content
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      summary: Upload new File
      tags:
      - File
  /file/{uid}:
    delete:
      description: Delete File
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: uid of File
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete File
      tags:
      - File
    get:
      description: Get File Info
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: uid of File
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get File Info
      tags:
      - File
    put:
      description: Change File
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: uid of File
        in: path
        name: uid
        required: true
        type: string
      - description: File to upload
        in: formData
        name: content
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      summary: Change File
      tags:
      - File
  /mail:
    get:
      description: Get Email histories
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get Email histories
      tags:
      - Email
    post:
      description: Send Email API
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: Send Email Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.SendEmailPayload'
      produces:
      - application/json
      responses: {}
      summary: Send Email API
      tags:
      - Email
  /mail/{uid}:
    get:
      description: Get Info Email History
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: String of Email History UID
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get Info Email History
      tags:
      - Email
  /rajaongkir:
    get:
      description: Get Rajaongkir Cost histories
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get Rajaongkir Cost histories
      tags:
      - Rajaongkir
  /rajaongkir/cost:
    post:
      description: Get delivery cost with Rajaongkir
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: Rajaongkir cost data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.CostInfoPayload'
      produces:
      - application/json
      responses: {}
      summary: Get delivery cost with Rajaongkir
      tags:
      - Rajaongkir
  /rajaongkir/province:
    get:
      description: Get Rajaongkir Province data
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get Rajaongkir Province data
      tags:
      - Rajaongkir
  /rajaongkir/province/{id}/city:
    get:
      description: Get Rajaongkir City data by Province ID
      parameters:
      - description: With value 'Bearer {authToken}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: number of Province ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get Rajaongkir City data by Province ID
      tags:
      - Rajaongkir
swagger: "2.0"
